dist: trusty
sudo: required
language: python
python:
- '3.6'
services:
- docker
script:
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
- docker pull budgetkey/open-budget-elasticsearch-commercial || true
- "./build.sh"
env:
  global:
  - secure: dMwx+3HKbR5WwIxLAY/xH/G/BHaixzU3AkgYfywSMf/EgXAp5ozoHyBlc/dZ2qaqOGasmCsXd7d9Vez6NCm/WZVJVoKCL+86SPrn1JJ7UAX2l21nnRlHT2UBMp/lu/7+Xf1hkbB8p9BwzKMh2gO9kNcOzEJkl3aeNHv8MS8u7j5O91h3D35B7ezRsDKsEEGNFPZrhWvc6UqXEyGzp1BAZ7wGLaOtmfOl/0wEF6eDAlpNS1zzJ/qkRVYrdsAEm+bnQmu0AUM1wsqwFCUWZLQvQ1wAoH/Rp2IO9uahrbF9QbsFiNGNmBfNkUKdaDXTWEC66dd6mGeksH6zqcHXC+bvdtkDhgb9Wfl3MR03zzjWCx6d66dTxYuVB6xRSHIFKpFBGj5EmJfZKZYOj0BAM0+W2qlxkL9Jz/V6c0jKFGAw0rJf3HJdEdQAxtMe7xrnVQzcPCpiyeatJYYTHdsXAPX/7+ZQB3tdyJIJqPeAySePQru9cqrXWOS4/y9ajUMsr3xpcpJM7Tux59+qkb9VDt8028NNIS2gXsiPALlnhMRpLmKqCnIv1zpOMxLA8PRmE04413aYMs10K0uu4m6SZRhxydzWvEH3v2tuLMXkR/QehV/Fet5zjcErEkP2khn+Sjs1Gfzrwgm4FmjU5/oxY32C+zeK2rHSAuLGy2LRK5cu3n4=
  - secure: qExy3yUJiu97d6qJcmn63QGQFE9ZdfZBzvJl2V4YiZ5L9y1bTfUlStNIm8GmLcqWVd7PxdSMkfjZzc+Qkh3eLOEREiBUlTpujFWk/JP72C/19mhj4iGVwFqcM41nWOY6qGndaq897p+6PHY37254NBkyWk+/YPlbTHsvJWELgkch9DE9tgvOA5kDK8la4B1nix38iHAer8ujTucdeQL7gJAD/Ziz025lSgbPO4gPBLc7segbTQmkKujgjEwyxf/c44ZSRCvXioLwNoQQqVlESIC03K7lcmxkbsOogoBvFOmh8OnFBw6E4Mby35rPa1fGE3Kn7QoFxTirM78J/6VEbHd+mZ/AGtOE9XQWUL9TJpUsR/lLn26PvtlAMlDRReASKLX3hSxsNDNFQWIjU6Lj5cUPLeS1lylhtFD/H92XgSeXWUUU7bALQ5ImIxTS+/OYHQN2WnvRYRXPgLjdV4HmH0hwtO/q5PONnUUVcUPik0bk+IU6Evc40hb9XsACsHIgvP6j8cP9I+tVWwR3S0LmDmB9GBTaLY/wzy+odSXGKiUpFbIN7v3FzPu1enUhImWL2feOExsHlotR842LwN6Z6pHnb7i1uypP2CzsWhHORW9lTjx3ODDL7NktT8WRM1yFNPK7JIR6o/48ZsSgor3jLvzZsxC/5u7rfMqUHc00L+Y=
